insert into TASK(STATUS, COLUMN_ID, ID, DESCRIPTION, TITLE) VALUES ( 0, 1, NEXTVAL('task_seq'), 'TESTE2', 'TESTE' );
insert into TASK(STATUS, COLUMN_ID, ID, DESCRIPTION, TITLE) VALUES ( 0, 1, NEXTVAL('task_seq'), 'TESTE3', 'TESTE' );
